annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Major chart redesign and also update to n8n version 1.74.1. This version is not compatible with the previous version. Please read the release notes for more details."
  artifacthub.io/prerelease: "true"
apiVersion: v2
appVersion: 1.76.1
dependencies:
- condition: redis.enabled
  name: valkey
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.2.3
description: A Kubernetes Helm chart for n8n a free and open fair-code licensed node
  based Workflow Automation Tool. Easily automate tasks across different services.
home: https://github.com/8gears/n8n-helm-chart
icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
keywords:
- Workflow Automation
- Workflow
- iPaaS
- integration-framework
- low-code-plattform
- low-code
maintainers:
- email: contact@8gears.com
  name: 8gears
  url: https://github.com/8gears
- email: _@8gears.com
  name: n8n
  url: https://github.com/n8n-io
name: n8n
sources:
- https://github.com/n8n-io/n8n
- https://n8n.io/
type: application
version: 1.0.0
